version: '3.8'

services:
  mongo:
    image: 'mongo:latest'
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_DATABASE: express-dashboard-starter
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - mongodb_network

  mongo-express:
    image: 'mongo-express'
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: test
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_BASICAUTH_USERNAME: test
      ME_CONFIG_BASICAUTH_PASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://test:test@mongo:27017/
    networks:
      - mongodb_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command: npm run start:dev
    container_name: 'express-dashboard-starter'
    ports:
      - 3000:3000
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - ./docs:/app/docs
    depends_on: [mongo]



networks:
  mongodb_network:
    driver: bridge
    name: mongo-network